name: Unity GitHub Packages Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: npm publish ./Packages/SamplePackage
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
      - run: npm publish ./Packages/SamplePackageCore
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        continue-on-error: true
